# ============================
# 1. Backend Deployment
# ============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: apisix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - name: httpbin
        image: kennethreitz/httpbin
        ports:
        - containerPort: 80

---
# ============================
# 2. Backend Service
# ============================
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: apisix
spec:
  selector:
    app: httpbin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
# ============================
# 3. APISIX Route
# ============================
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: httpbin-route
  namespace: apisix
spec:
  http:
  - name: rule1
    match:
      hosts:
      - example.com        # Change to your domain
      paths:
      - /*
    backends:
    - serviceName: httpbin
      servicePort: 80

