---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-manager-declarative
  namespace: default
data:
  kong.yml: |
    _format_version: "2.1"
    services:
      - name: httpbin
        url: http://httpbin.default.svc.cluster.local:80
        routes:
          - name: httpbin-route
            paths:
              - /
    plugins:
      - name: basic-auth
        config:
          hide_credentials: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-manager
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-manager
  template:
    metadata:
      labels:
        app: kong-manager
    spec:
      containers:
        - name: kong-manager
          image: kong:3.9
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: "/kong/declarative/kong.yml"
            - name: KONG_PROXY_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_PROXY_ERROR_LOG
              value: "/dev/stderr"
            - name: KONG_ADMIN_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_ADMIN_ERROR_LOG
              value: "/dev/stderr"
            - name: KONG_ADMIN_LISTEN
              value: "0.0.0.0:8001 ssl"
          ports:
            - containerPort: 8001
              name: admin
          volumeMounts:
            - name: declarative
              mountPath: /kong/declarative
            - name: tls-cert
              mountPath: /etc/secrets/kong-manager
              readOnly: true
      volumes:
        - name: declarative
          configMap:
            name: kong-manager-declarative
        - name: tls-cert
          secret:
            secretName: kong-manager-tls
---
apiVersion: v1
kind: Service
metadata:
  name: kong-manager
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 8001
      protocol: TCP
      name: https
  selector:
    app: kong-manager
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-manager
  namespace: default
  annotations:
    konghq.com/strip-path: "false"
spec:
  ingressClassName: kong
  tls:
    - hosts:
        - kong-manager.nccnaga.com
      secretName: kong-manager-tls
  rules:
    - host: kong-manager.nccnaga.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kong-manager
                port:
                  number: 443
