---
apiVersion: v1
kind: Service
metadata:
  name: dummy-backend
  namespace: default
spec:
  selector:
    app: dummy-backend
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-backend
  template:
    metadata:
      labels:
        app: dummy-backend
    spec:
      containers:
        - name: dummy-backend
          image: hashicorp/http-echo
          args:
            - "-text=Hello from dummy backend!"
          ports:
            - containerPort: 8080
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: test-https-route
  namespace: default
spec:
  http:
    - name: test-https
      match:
        hosts:
          - mlm.nccnaga.com
        paths:
          - /*
      backends:
        - serviceName: dummy-backend
          servicePort: 80
