kind: Deployment
apiVersion: apps/v1
metadata:
  name: apisix
  namespace: default
  labels:
    app.kubernetes.io/instance: apisix
    app.kubernetes.io/name: apisix
    app.kubernetes.io/version: 2.10.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: apisix
      app.kubernetes.io/name: apisix
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: apisix
        app.kubernetes.io/name: apisix
    spec:
      volumes:
        - name: apisix-config
          configMap:
            name: apisix
            defaultMode: 420
        - name: tls-secret
          secret:
            secretName: mlm.nccnaga.com-tls
      initContainers:
        - name: wait-etcd
          image: busybox:1.28
          command:
            - sh
            - '-c'
            - >
              until nc -z apisix-etcd.default.svc.cluster.local 2379; do echo
              waiting for etcd `date`; sleep 2; done;
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      containers:
        - name: apisix
          image: apache/apisix:2.10.0-alpine
          ports:
            - name: http
              containerPort: 9080
              protocol: TCP
            - name: tls
              containerPort: 9443
              protocol: TCP
            - name: admin
              containerPort: 9180
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: apisix-config
              mountPath: /usr/local/apisix/conf
            - name: tls-secret
              mountPath: /usr/local/apisix/conf/tls
              readOnly: true
          readinessProbe:
            tcpSocket:
              port: 9080
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - sleep 30
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix
  namespace: default
data:
  config.yaml: |-
    apisix:
      node_listen: 9080
      enable_heartbeat: true
      enable_admin: true
      enable_admin_cors: true
      enable_debug: false
      enable_dev_mode: false
      enable_reuseport: true
      enable_ipv6: true
      config_center: etcd
      allow_admin:
        - 0.0.0.0/0
      port_admin: 9180
      admin_key:
        - name: "admin"
          key: edw1c9f036335f186f87ad84b625c8f2
          role: admin
      router:
        http: 'radixtree_uri'
        ssl: 'radixtree_sni'
      dns_resolver_valid: 30
      resolver_timeout: 5
      ssl:
        enable: true
        enable_http2: true
        listen_port: 9443
        ssl_protocols: "TLSv1.2 TLSv1.3"
        ssl_ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305"
        cert: "/usr/local/apisix/conf/tls/tls.crt"
        cert_key: "/usr/local/apisix/conf/tls/tls.key"
      etcd:
        host:
          - "http://apisix-etcd.default.svc.cluster.local:2379"
        prefix: "/apisix"
        timeout: 30

  config-default.yaml: |-
    apisix:
      node_listen: 9080
      enable_admin: true
      enable_reuseport: true
      enable_ipv6: true
      config_center: etcd
      port_admin: 9180
      etcd:
        host:
          - "http://apisix-etcd.default.svc.cluster.local:2379"
        prefix: "/apisix"
        timeout: 30
      router:
        http: 'radixtree_uri'
        ssl: 'radixtree_sni'
      ssl:
        enable: true
---
kind: Service
apiVersion: v1
metadata:
  name: apisix-admin
  namespace: default
spec:
  ports:
    - name: apisix-admin
      protocol: TCP
      port: 9180
      targetPort: 9180
  selector:
    app.kubernetes.io/instance: apisix
    app.kubernetes.io/name: apisix
  type: ClusterIP
---
kind: Service
apiVersion: v1
metadata:
  name: apisix-gateway
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: apisix
    app.kubernetes.io/name: apisix
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9080
      nodePort: 31684
    - name: https
      protocol: TCP
      port: 443
      targetPort: 9443
      nodePort: 32139
  sessionAffinity: None
  externalTrafficPolicy: Cluster
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: mlm-nccnaga-com-tls
  namespace: default
spec:
  hosts:
    - mlm.nccnaga.com
  secret:
    name: mlm.nccnaga.com-tls
    namespace: default
