---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix
  namespace: default
data:
  config.yaml: |-
    apisix:
      node_listen: 9080
      enable_heartbeat: true
      enable_admin: true
      enable_admin_cors: true
      enable_debug: false
      enable_dev_mode: false
      enable_reuseport: true
      enable_ipv6: true
      config_center: etcd

      allow_admin:
        - 0.0.0.0/0
      port_admin: 9180

      admin_key:
        - name: "admin"
          key: edw1c9f036335f186f87ad84b625c8f2
          role: admin

      router:
        http: 'radixtree_uri'
        ssl: 'radixtree_sni'

      dns_resolver_valid: 30
      resolver_timeout: 5

      ssl:
        enable: true
        enable_http2: true
        listen_port: 9443
        ssl_protocols: "TLSv1.2 TLSv1.3"
        ssl_ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384"
        cert: "/usr/local/apisix/conf/tls/tls.crt"
        cert_key: "/usr/local/apisix/conf/tls/tls.key"

      etcd:
        host:
          - "http://apisix-etcd.default.svc.cluster.local:2379"
        prefix: "/apisix"
        timeout: 30

      plugins:
        - api-breaker
        - basic-auth
        - cors
        - proxy-cache
        - request-id
        - server-info

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: apisix
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apisix
    spec:
      volumes:
        - name: apisix-config
          configMap:
            name: apisix
        - name: tls-secret
          secret:
            secretName: mlm.nccnaga.com-tls
      initContainers:
        - name: wait-etcd
          image: busybox:1.28
          command:
            - sh
            - '-c'
            - >-
              until nc -z apisix-etcd.default.svc.cluster.local 2379; do echo waiting for etcd `date`; sleep 2; done;
      containers:
        - name: apisix
          image: apache/apisix:2.10.0-alpine
          ports:
            - containerPort: 9080
              name: http
            - containerPort: 9443
              name: tls
            - containerPort: 9180
              name: admin
          volumeMounts:
            - name: apisix-config
              mountPath: /usr/local/apisix/conf/config.yaml
              subPath: config.yaml
            - name: tls-secret
              mountPath: /usr/local/apisix/conf/tls
              readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: apisix-admin
  namespace: default
spec:
  ports:
    - name: admin
      port: 9180
      targetPort: 9180
  selector:
    app.kubernetes.io/name: apisix
---
apiVersion: v1
kind: Service
metadata:
  name: apisix-gateway
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: apisix
  ports:
    - name: http
      port: 80
      targetPort: 9080
    - name: https
      port: 443
      targetPort: 9443
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: mlm-nccnaga-com-tls
  namespace: default
spec:
  hosts:
    - mlm.nccnaga.com
  secret:
    name: mlm.nccnaga.com-tls
    namespace: default
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apisix-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "apisix"
spec:
  rules:
    - host: mlm.nccnaga.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apisix-gateway
                port:
                  number: 80
  tls:
    - hosts:
        - mlm.nccnaga.com
      secretName: mlm.nccnaga.com-tls

