---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix
  namespace: default
data:
  config.yaml: |-
    apisix:
      node_listen: 9080
      enable_heartbeat: true
      enable_admin: true
      enable_admin_cors: true
      enable_debug: false
      enable_dev_mode: false
      enable_reuseport: true
      enable_ipv6: true
      config_center: etcd

      allow_admin:
        - 0.0.0.0/0
      port_admin: 9180
      admin_key:
        - name: "admin"
          key: edw1c9f036335f186f87ad84b625c8f2
          role: admin
        - name: "viewer"
          key: 9054f7cf07e3224336cd3f287985e76a41
          role: viewer

      router:
        http: "radixtree_uri"
        ssl: "radixtree_sni"

      dns_resolver_valid: 30
      resolver_timeout: 5

      ssl:
        enable: true
        enable_http2: true
        listen_port: 9443
        ssl_protocols: "TLSv1.2 TLSv1.3"
        ssl_ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305"
        cert: "/usr/local/apisix/conf/tls/tls.crt"
        cert_key: "/usr/local/apisix/conf/tls/tls.key"

      etcd:
        host:
          - "http://apisix-etcd.default.svc.cluster.local:2379"
        prefix: "/apisix"
        timeout: 30

      proxy_cache:
        cache_ttl: 10s
        zones:
          - name: disk_cache_one
            memory_size: 500m
            disk_size: 1G
            disk_path: "/tmp/disk_cache_one"
            cache_levels: "1:2"

    nginx_config:
      error_log: "/dev/stderr"
      error_log_level: "warn"
      worker_rlimit_nofile: 20480
      event:
        worker_connections: 10620
      http:
        access_log: "/dev/stdout"
        keepalive_timeout: 60s
        client_header_timeout: 60s
        client_body_timeout: 60s
        send_timeout: 10s
        underscores_in_headers: "on"
        real_ip_header: "X-Real-IP"
        real_ip_from:
          - 127.0.0.1
          - 'unix:'
        server-snippets: |
          server {
              listen 9443 ssl;
              server_name _;
              return 444;
          }

    plugins:
      - api-breaker
      - basic-auth
      - cors
      - key-auth
      - limit-count
      - limit-req
      - node-status
      - proxy-cache
      - real-ip
      - server-info
      - traffic-split
      - gzip

    stream_plugins:
      - ip-restriction
      - limit-conn

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apisix
  template:
    metadata:
      labels:
        app: apisix
    spec:
      volumes:
        - name: apisix-config
          configMap:
            name: apisix
        - name: tls-secret
          secret:
            secretName: mlm.nccnaga.com-tls
      initContainers:
        - name: wait-etcd
          image: busybox:1.28
          command:
            - sh
            - '-c'
            - >-
              until nc -z apisix-etcd.default.svc.cluster.local 2379; do echo waiting for etcd `date`; sleep 2; done;
      containers:
        - name: apisix
          image: apache/apisix:2.10.0-alpine
          ports:
            - name: http
              containerPort: 9080
            - name: https
              containerPort: 9443
            - name: admin
              containerPort: 9180
          volumeMounts:
            - name: apisix-config
              mountPath: /usr/local/apisix/conf/config.yaml
              subPath: config.yaml
            - name: tls-secret
              mountPath: /usr/local/apisix/conf/tls
              readOnly: true
          readinessProbe:
            tcpSocket:
              port: 9080
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - sleep 30
---
apiVersion: v1
kind: Service
metadata:
  name: apisix-admin
  namespace: default
spec:
  selector:
    app: apisix
  ports:
    - name: admin
      port: 9180
      targetPort: 9180
---
apiVersion: v1
kind: Service
metadata:
  name: apisix-gateway
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: apisix
  ports:
    - name: http
      port: 80
      targetPort: 9080
    - name: https
      port: 443
      targetPort: 9443
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: mlm-nccnaga-com-tls
  namespace: default
spec:
  hosts:
    - mlm.nccnaga.com
  secret:
    name: mlm.nccnaga.com-tls
    namespace: default
