apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apisix
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.apiseven.com
    chart: apisix
    targetRevision: 2.11.5
    helm:
      values: |
        gateway:
          type: LoadBalancer
        admin:
          type: ClusterIP
          port: 9180
        etcd:
          enabled: true
        apisix:
          # Point APISIX to the internal ETCD service
          extraEnvVars:
            - name: ETCD_HOST
              value: "http://apisix-etcd-headless.default.svc.cluster.local:2379"
          extraInitContainers:
            - name: wait-etcd
              image: busybox
              command: ['sh', '-c', 'until nc -z apisix-etcd-headless.default.svc.cluster.local 2379; do echo waiting for etcd; sleep 2; done']
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
