# ============================
# 1. Patch APISIX Gateway to LoadBalancer
# ============================
apiVersion: v1
kind: Service
metadata:
  name: apisix-gateway
  namespace: apisix
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
  selector:
    app.kubernetes.io/instance: apisix
    app.kubernetes.io/name: apisix
# ============================
# 1. Backend Deployment
# ============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - name: httpbin
        image: kennethreitz/httpbin
        ports:
        - containerPort: 80

---
# ============================
# 2. Backend Service
# ============================
apiVersion: v1
kind: Service
metadata:
  name: apisix
  namespace: default
spec:
  selector:
    app: httpbin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
# ============================
# 3. APISIX Route
# ============================
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: httpbin-route
  namespace: default
spec:
  http:
  - name: rule1
    match:
      hosts:
      - mlm.nccnaga.com       # Change to your domain
      paths:
      - /*
    backends:
    - serviceName: httpbin
      servicePort: 80
