apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apisix
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.apiseven.com
    chart: apisix
    targetRevision: 2.11.5
    helm:
      values: |
        gateway:
          type: LoadBalancer
          externalTrafficPolicy: Cluster
        admin:
          type: ClusterIP
          port: 9180
        etcd:
          enabled: true
          service:
            type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
