kind: Deployment
apiVersion: apps/v1
metadata:
  name: apisix
  namespace: default
  labels:
    app.kubernetes.io/instance: apisix
    app.kubernetes.io/name: apisix
    app.kubernetes.io/version: 2.10.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: apisix
      app.kubernetes.io/name: apisix
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: apisix
        app.kubernetes.io/name: apisix
    spec:
      volumes:
        - name: apisix-config
          configMap:
            name: apisix
            defaultMode: 420
      initContainers:
        - name: wait-etcd
          image: busybox:1.28
          command:
            - sh
            - '-c'
            - >-
              until nc -z apisix-etcd.default.svc.cluster.local 2379; do echo
              waiting for etcd `date`; sleep 2; done;
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      containers:
        - name: apisix
          image: apache/apisix:2.10.0-alpine
          ports:
            - name: http
              containerPort: 9080
              protocol: TCP
            - name: tls
              containerPort: 9443
              protocol: TCP
            - name: admin
              containerPort: 9180
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: apisix-config
              mountPath: /usr/local/apisix/conf/config.yaml
              subPath: config.yaml
          readinessProbe:
            tcpSocket:
              port: 9080
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - sleep 30
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: apisix
  namespace: default
data:
  config.yaml: >-
    #

    # Licensed to the Apache Software Foundation (ASF) under one or more

    # contributor license agreements.  See the NOTICE file distributed with

    # this work for additional information regarding copyright ownership.

    # The ASF licenses this file to You under the Apache License, Version 2.0

    # (the "License"); you may not use this file except in compliance with

    # the License.  You may obtain a copy of the License at

    #

    #     http://www.apache.org/licenses/LICENSE-2.0

    #

    # Unless required by applicable law or agreed to in writing, software

    # distributed under the License is distributed on an "AS IS" BASIS,

    # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

    # See the License for the specific language governing permissions and

    # limitations under the License.

    #

    apisix:
      node_listen: 9080             # APISIX listening port
      enable_heartbeat: true
      enable_admin: true
      enable_admin_cors: true
      enable_debug: false
      enable_dev_mode: false          # Sets nginx worker_processes to 1 if set to true
      enable_reuseport: true          # Enable nginx SO_REUSEPORT switch if set to true.
      enable_ipv6: true
      config_center: etcd             # etcd: use etcd to store the config value
                                      # yaml: fetch the config value from local yaml file `/your_path/conf/apisix.yaml`


      #proxy_protocol:                 # Proxy Protocol configuration
      #  listen_http_port: 9181        # The port with proxy protocol for http, it differs from node_listen and port_admin.
                                      # This port can only receive http request with proxy protocol, but node_listen & port_admin
                                      # can only receive http request. If you enable proxy protocol, you must use this port to
                                      # receive http request with proxy protocol
      #  listen_https_port: 9182       # The port with proxy protocol for https
      #  enable_tcp_pp: true           # Enable the proxy protocol for tcp proxy, it works for stream_proxy.tcp option
      #  enable_tcp_pp_to_upstream: true # Enables the proxy protocol to the upstream server

      proxy_cache:                     # Proxy Caching configuration
        cache_ttl: 10s                 # The default caching time if the upstream does not specify the cache time
        zones:                         # The parameters of a cache
        - name: disk_cache_one         # The name of the cache, administrator can be specify
                                      # which cache to use by name in the admin api
          memory_size: 50m             # The size of shared memory, it's used to store the cache index
          disk_size: 1G                # The size of disk, it's used to store the cache data
          disk_path: "/tmp/disk_cache_one" # The path to store the cache data
          cache_levels: "1:2"           # The hierarchy levels of a cache
      #  - name: disk_cache_two
      #    memory_size: 50m
      #    disk_size: 1G
      #    disk_path: "/tmp/disk_cache_two"
      #    cache_levels: "1:2"

      allow_admin:                  # http://nginx.org/en/docs/http/ngx_http_access_module.html#allow
        - 127.0.0.1/24
      #   - "::/64"
      port_admin: 9180

      # Default token when use API to call for Admin API.
      # *NOTE*: Highly recommended to modify this value to protect APISIX's Admin API.
      # Disabling this configuration item means that the Admin API does not
      # require any authentication.
      admin_key:
        # admin: can everything for configuration data
        - name: "admin"
          key: edw1c9f036335f186f87ad84b625c8f2
          role: admin
        # viewer: only can view configuration data
        - name: "viewer"
          key: 4054f7cf07e344346cd3f287985e76a2
          role: viewer
      router:
        http: 'radixtree_uri'         # radixtree_uri: match route by uri(base on radixtree)
                                      # radixtree_host_uri: match route by host + uri(base on radixtree)
        ssl: 'radixtree_sni'          # radixtree_sni: match route by SNI(base on radixtree)
      # dns_resolver:
      #
      #   - 127.0.0.1
      #
      #   - 172.20.0.10
      #
      #   - 114.114.114.114
      #
      #   - 223.5.5.5
      #
      #   - 1.1.1.1
      #
      #   - 8.8.8.8
      #
      dns_resolver_valid: 30
      resolver_timeout: 5
      ssl:
        enable: true
        enable_http2: true
        listen_port: 9443
        ssl_protocols: "TLSv1 TLSv1.1 TLSv1.2 TLSv1.3"
        ssl_ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA"
        certificates:
          - cert: |
              -----BEGIN CERTIFICATE-----
              MIIEszCCA5ugAwIBAgIUHt6tTW3Sh1sOaek0YWadvaUpPQowDQYJKoZIhvcNAQEL
              BQAwgYsxCzAJBgNVBAYTAlVTMRkwFwYDVQQKExBDbG91ZEZsYXJlLCBJbmMuMTQw
              MgYDVQQLEytDbG91ZEZsYXJlIE9yaWdpbiBTU0wgQ2VydGlmaWNhdGUgQXV0aG9y
              aXR5MRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMRMwEQYDVQQIEwpDYWxpZm9ybmlh
              MB4XDTI1MDgxODAyMzMwMFoXDTQwMDgxNDAyMzMwMFowYjEZMBcGA1UEChMQQ2xv
              dWRGbGFyZSwgSW5jLjEdMBsGA1UECxMUQ2xvdWRGbGFyZSBPcmlnaW4gQ0ExJjAk
              BgNVBAMTHUNsb3VkRmxhcmUgT3JpZ2luIENlcnRpZmljYXRlMIIBIjANBgkqhkiG
              9w0BAQEFAAOCAQ8AMIIBCgKCAQEAplV6YUAEj8yIioLIUO9EHmUuwzFyZXAjnebe
              2jTxj4GiV8a3yxFrPevGZg8DpiBcZYNLozolotKhQrOqPyCETX72qPB1Xac/x3TJ
              eQf1/qmXVseSdn+vt//fqfiUcZKjCo4gy475SPE3mPK0d08EwcDoC+SZsZBmrDaL
              Op982A95hxO9KRuAC/XgTVJOuKE8nAWrqGuKCKlAZztL46GDCGAGdqABN21U0iro
              C4xs/H7tIg+8cAdsieeD0isO2bul/4yGWy3h+y8+wv71Qp1jTTGkBX7oRLWI3wMm
              gO1h1pMl9zvTIRsOxYSgwchkEaciUQ2DEAniuDHiykL9uFgwXwIDAQABo4IBNTCC
              ATEwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcD
              ATAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBSSwhfMsepF4wyckW7kmLocAR1uSzAf
              BgNVHSMEGDAWgBQk6FNXXXw0QIep65TbuuEWePwppDBABggrBgEFBQcBAQQ0MDIw
              MAYIKwYBBQUHMAGGJGh0dHA6Ly9vY3NwLmNsb3VkZmxhcmUuY29tL29yaWdpbl9j
              YTA2BgNVHREELzAtgg0qLm5jY25hZ2EuY29tgg9tbG0ubmNjbmFnYS5jb22CC25j
              Y25hZ2EuY29tMDgGA1UdHwQxMC8wLaAroCmGJ2h0dHA6Ly9jcmwuY2xvdWRmbGFy
              ZS5jb20vb3JpZ2luX2NhLmNybDANBgkqhkiG9w0BAQsFAAOCAQEAeJH2uh2WJSto
              Ha98KO/4ilRC03/cRrFbzTF+xaJNYHpCc+7uHYWetwjHlHno329m3vWhReoAOuqB
              GG5ugLR7WDHOU+CUGCG08R5KIIhJ6O6ccV6cdw8pDeKdsHh4g9Mqbfu7yhXClSpb
              2zxu4moUAeM4MA4eQjE5miFVLPGXlnJ0cjmwlL7mcgaexwNoOhY08LYVBiWNK/G8
              yKnuWz7kfJsmDV37hGS8R/n+glPIwvcNnuYg3jkpU/pZW1GIN63mbt2HdHzs9He6
              9L49viUgDHQocRtZ2iYLF6+GTA4V0Q0GZJEmtNlqjXIKdxaHdYYNQGNr/nBnItPf
              4+V0PkQ4Ow==
              -----END CERTIFICATE-----
            key: |
              -----BEGIN PRIVATE KEY-----
              MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCmVXphQASPzIiK
              gshQ70QeZS7DMXJlcCOd5t7aNPGPgaJXxrfLEWs968ZmDwOmIFxlg0ujOiWi0qFC
              s6o/IIRNfvao8HVdpz/HdMl5B/X+qZdWx5J2f6+3/9+p+JRxkqMKjiDLjvlI8TeY
              8rR3TwTBwOgL5JmxkGasNos6n3zYD3mHE70pG4AL9eBNUk64oTycBauoa4oIqUBn
              O0vjoYMIYAZ2oAE3bVTSKugLjGz8fu0iD7xwB2yJ54PSKw7Zu6X/jIZbLeH7Lz7C
              /vVCnWNNMaQFfuhEtYjfAyaA7WHWkyX3O9MhGw7FhKDByGQRpyJRDYMQCeK4MeLK
              Qv24WDBfAgMBAAECggEAIAFxn3XkitD18wUQS3aGunyIv3lrxDYMPG14sy8dzhnJ
              Ja+wnOv4oT0Ve3znHFe8v7HAY6OkK0zxR7bvit8UZh8IkmBWjRNKE/SWceoEvSBf
              5QxY0+Fk6/hZzshss9/d7IGFsPWNZSo5Iv6MmCqFxUx7uhIeOssI3plOOBUJPj+I
              noZU6k2/zOCU7wURjXGZDay+QhRdpoS7RwfXc9o43sHpZ2m90ztMgoyRXbk/xdtV
              jiDV6+cTRh3aUE51GYPq01k5K0wJULySftoc2HRPaJNWyFGPD4gz6b+C6fXCrbp4
              iDzSIuLFcM0BN3eQSLn7sO43o1TnJfHgWTZ3NbhHuQKBgQDO8jIM0Or6HirpukHk
              vs4bOgpMYHXDW3zaFJVLEsjAZEOvJ8z9W62jDp9KqTqkmaN4rlXCHBDEztKX72HG
              6D10O8WpCuCv1FvBWQ1FR8jxNNI2GukAVl4CtmVWrYmIbCtvEtNE/2kTk6nowy3/
              4VtVz4nT7KZ6qYPjb1MLSXKzZwKBgQDNwt+b+FuEgVmHD8AAhkLF9r+ZPiRpctUC
              j4cBLWIZYCOGL3eWNJ8/zLg6GSyczxPH0Sbb2h6kyIc8Nj8WRLmOcQVJzzyWeK4h
              1vIW5F05L1kUAx87QLS8MIZpgvdE3dyHUuWo7JSrt3aoMO6+w4fPFflgCUK7sELn
              +jLmVye4SQKBgEk5T1ZTkeEgTYTX/7rFfL4LgltWAjU2qO2tPMoMgnX4xC40wgaf
              qse4Q8qyKGrXZg0senGtZo2MtN1HuWwc/qmjAKR4kdoFJNY8AUMTTFl0nDDCwtD4
              vljtWtwZmUFpLNEncxPF39Mqe4M9lIgmoB+zyIvw/1MFqgIOgO7MdUZfAoGAGPaO
              iG6uM7o5sWAgzC99xGS2RBI8+qoa26+sEmF+KFP4m1wA5zFFLMlahHnvZqrc3H4s
              d7nTw+wsNArkxn/Z/0UI/jZtRFgp0CMyxcI46SosZXgnftnP05ETjZN9ClbcXXKa
              OE9Tji248JjXLj+sp1wkIBmfhgPRajF5oWZrhDkCgYA1xcskYXp5mmhfpNRLVgJx
              rQR3P7cEYFVKSsG6ZJubzZ+g8VHSmCYLhMO/CN8/jbEYvzjIemPKUQfmnXNecqC6
              b49fYPUmzdp1lSNzEJ7Yrq8IISwN2jZFcxqySthX3Im80imwTwydwsyWFe/OOte3
              qnH46wmjXkg6RygINOGbJw==
              -----END PRIVATE KEY-----
            sni: "mlm.nccnaga.com"
    nginx_config:                     # config for render the template to
    genarate nginx.conf
      error_log: "/dev/stderr"
      error_log_level: "warn"         # warn,error
      worker_rlimit_nofile: 20480     # the number of files a worker process can open, should be larger than worker_connections
      event:
        worker_connections: 10620
      http:
        access_log: "/dev/stdout"
        keepalive_timeout: 60s         # timeout during which a keep-alive client connection will stay open on the server side.
        client_header_timeout: 60s     # timeout for reading client request header, then 408 (Request Time-out) error is returned to the client
        client_body_timeout: 60s       # timeout for reading client request body, then 408 (Request Time-out) error is returned to the client
        send_timeout: 10s              # timeout for transmitting a response to the client.then the connection is closed
        underscores_in_headers: "on"   # default enables the use of underscores in client request header fields
        real_ip_header: "X-Real-IP"    # http://nginx.org/en/docs/http/ngx_http_realip_module.html#real_ip_header
        real_ip_from:                  # http://nginx.org/en/docs/http/ngx_http_realip_module.html#set_real_ip_from
          - 127.0.0.1
          - 'unix:'

    etcd:
      host:                                 # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
        - "http://apisix-etcd.default.svc.cluster.local:2379"
      prefix: "/apisix"     # apisix configurations prefix
      timeout: 30   # 30 seconds
    plugins:                          # plugin list
      - api-breaker
      - authz-keycloak
      - basic-auth
      - batch-requests
      - consumer-restriction
      - cors
      - echo
      - fault-injection
      - grpc-transcode
      - hmac-auth
      - http-logger
      - ip-restriction
      - ua-restriction
      - jwt-auth
      - kafka-logger
      - key-auth
      - limit-conn
      - limit-count
      - limit-req
      - node-status
      - openid-connect
      - authz-casbin
      - prometheus
      - proxy-cache
      - proxy-mirror
      - proxy-rewrite
      - redirect
      - referer-restriction
      - request-id
      - request-validation
      - response-rewrite
      - serverless-post-function
      - serverless-pre-function
      - sls-logger
      - syslog
      - tcp-logger
      - udp-logger
      - uri-blocker
      - wolf-rbac
      - zipkin
      - server-info
      - traffic-split
      - gzip
      - real-ip
    stream_plugins:
      - mqtt-proxy
      - ip-restriction
      - limit-conn
    plugin_attr:
      server-info:
        report_interval: 60
        report_ttl: 3600
---
kind: Service
apiVersion: v1
metadata:
  name: apisix-admin
  namespace: default
  labels:
    app.kubernetes.io/instance: apisix
    app.kubernetes.io/name: apisix
    app.kubernetes.io/version: 2.10.0
spec:
  ports:
    - name: apisix-admin
      protocol: TCP
      port: 9180
      targetPort: 9180
  selector:
    app.kubernetes.io/instance: apisix
    app.kubernetes.io/name: apisix
  type: ClusterIP
---
kind: Service
apiVersion: v1
metadata:
  name: apisix-gateway
  namespace: default
  labels:
    app.kubernetes.io/instance: apisix
    app.kubernetes.io/name: apisix
    app.kubernetes.io/version: 2.10.0
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: apisix
    app.kubernetes.io/name: apisix
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9080
      nodePort: 31684
    - name: https
      protocol: TCP
      port: 443
      targetPort: 9443
      nodePort: 32139
  sessionAffinity: None
  externalTrafficPolicy: Cluster

