apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: my-app-route
  namespace: default
spec:
  tls:
    - hosts:
        - mlm.nccnaga.com
      secretName: apisix-tls
  http:
    - name: my-app-rule
      match:
        hosts:
          - mlm.nccnaga.com
        paths:
          - /*
      backends:
        - serviceName: my-app
          servicePort: 8080
