# ============================
# 1. Embedded etcd Deployment + Service
# ============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix-etcd
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apisix-etcd
  template:
    metadata:
      labels:
        app: apisix-etcd
    spec:
      containers:
      - name: etcd
        image: bitnami/etcd:latest
        env:
          - name: ALLOW_NONE_AUTHENTICATION
            value: "yes"
        ports:
          - containerPort: 2379
---
apiVersion: v1
kind: Service
metadata:
  name: apisix-etcd
  namespace: default
spec:
  selector:
    app: apisix-etcd
  ports:
    - port: 2379
      targetPort: 2379

# ============================
# 2. APISIX Deployment + LoadBalancer Service
# ============================
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apisix
  template:
    metadata:
      labels:
        app: apisix
    spec:
      containers:
      - name: apisix
        image: apache/apisix:3.13.0-debian
        env:
          - name: ETCD_HOST
            value: "apisix-etcd.default.svc.cluster.local:2379"
        ports:
          - containerPort: 80
          - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: apisix-gateway
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
    - port: 443
      targetPort: 443
  selector:
    app: apisix

# ============================
# 3. Self-Signed TLS Secret
# ============================
apiVersion: v1
kind: Secret
metadata:
  name: apisix-tls
  namespace: default
type: kubernetes.io/tls
data:
  # Replace these with your base64-encoded self-signed cert & key if you generate new ones
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURZRENDQW1tZ0F3SUJBZ0lKQUx1Qk9XZ2dGQU5CZ2txaGtpRzl3MEJBUXNGQURCd01EQXdNREF4TkRReApNRFF4TURVd01qRXhNREF4TURVd01qRXhNREF4TURVd01qRXhNREF4TURVeE1EWXhNREF4TURVeE1EWXhNREF4TURVeE1EWXhNREF4TURVeE1EWQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFbmR... (shortened example)
# You can generate a self-signed cert using:
# openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt -subj "/CN=example.mlm.nccnaga.com"

# ============================
# 4. APISIXRoute (no backend)
# ============================
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: example-route
  namespace: default
  annotations:
    kubernetes.io/ingress.class: apisix
spec:
  tls:
    - hosts:
        - example.mlm.nccnaga.com
      secretName: apisix-tls
  http:
    - name: example-rule
      match:
        hosts:
          - example.mlm.nccnaga.com
        paths:
          - /*
      backends: []
