# -------------------------------
# Deployment v1
# -------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-v1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin-v1
  template:
    metadata:
      labels:
        app: httpbin-v1
    spec:
      containers:
        - name: httpbin
          image: kennethreitz/httpbin
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - name: http
              containerPort: 80
      imagePullSecrets:
        - name: docker-hub
---
# -------------------------------
# Deployment v2
# -------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-v2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin-v2
  template:
    metadata:
      labels:
        app: httpbin-v2
    spec:
      containers:
        - name: httpbin
          image: kennethreitz/httpbin
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - name: http
              containerPort: 80
      imagePullSecrets:
        - name: docker-hub
---
# -------------------------------
# Services for both versions
# -------------------------------
apiVersion: v1
kind: Service
metadata:
  name: httpbin-v1
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: httpbin-v1
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-v2
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: httpbin-v2
---
# -------------------------------
# KongPlugin for Weighted Routing
# -------------------------------
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: traffic-split
  namespace: default
plugin: traffic-split
config:
  rules:
    - weight: 80
      upstream:
        service: httpbin-v1.default.svc
        port: 80
    - weight: 20
      upstream:
        service: httpbin-v2.default.svc
        port: 80
---
# -------------------------------
# Advanced Route Config
# -------------------------------
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: advanced-route
route:
  methods:
    - GET
    - POST
  headers:
    X-Api-Version:
      - v1
  paths:
    - /get
    - /api
  strip_path: true
  preserve_host: true
---
# -------------------------------
# Ingress (attach traffic-split plugin)
# -------------------------------
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin-ingress
  annotations:
    konghq.com/override: advanced-route
    konghq.com/plugins: traffic-split
spec:
  ingressClassName: kong
  rules:
    - host: mlm.nccnaga.com
      http:
        paths:
          - path: /get
            pathType: Prefix
            backend:
              service:
                name: httpbin-v1   # Kong will override with traffic-split
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: httpbin-v1   # Kong will override with traffic-split
                port:
                  number: 80
