# -------------------------------
# Deployment v1
# -------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-v1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin-v1
  template:
    metadata:
      labels:
        app: httpbin-v1
    spec:
      containers:
        - name: httpbin
          image: kennethreitz/httpbin
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - name: http
              containerPort: 80
      imagePullSecrets:
        - name: docker-hub
---
# -------------------------------
# Deployment v2
# -------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-v2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin-v2
  template:
    metadata:
      labels:
        app: httpbin-v2
    spec:
      containers:
        - name: httpbin
          image: kennethreitz/httpbin
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - name: http
              containerPort: 80
      imagePullSecrets:
        - name: docker-hub
---
# -------------------------------
# Services for both versions
# -------------------------------
apiVersion: v1
kind: Service
metadata:
  name: httpbin-v1
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: httpbin-v1
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-v2
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: httpbin-v2
---
# -------------------------------
# Ingress httpbin
# -------------------------------
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "kong"
spec:
  rules:
    - host: mlm.nccnaga.com
      http:
        paths:
          - path: /get
            pathType: Prefix
            backend:
              service:
                name: httpbin-v1   # Kong uses upstream, so service here is just a placeholder
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: httpbin-v1
                port:
                  number: 80
