# -------------------------------
# Deployment v1
# -------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-v1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin-v1
  template:
    metadata:
      labels:
        app: httpbin-v1
    spec:
      containers:
        - name: httpbin
          image: kennethreitz/httpbin
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - name: http
              containerPort: 80
      imagePullSecrets:
        - name: docker-hub
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-v1
  namespace: default
spec:
  selector:
    app: httpbin-v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
# -------------------------------
# Deployment v2
# -------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-v2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin-v2
  template:
    metadata:
      labels:
        app: httpbin-v2
    spec:
      containers:
        - name: httpbin
          image: kennethreitz/httpbin
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - name: http
              containerPort: 80
      imagePullSecrets:
        - name: docker-hub
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-v2
  namespace: default
spec:
  selector:
    app: httpbin-v2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

