apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-declarative-config
  namespace: default
data:
  kong.yaml: |
    _format_version: "2.1"
    _transform: true

    upstreams:
      - name: httpbin-upstream
        targets:
          - target: httpbin-v1.default.svc.cluster.local:80
            weight: 80
          - target: httpbin-v2.default.svc.cluster.local:80
            weight: 20

    services:
      - name: httpbin
        url: "http://httpbin-upstream"
        routes:
          - name: httpbin-route
            hosts:
              - "mlm.nccnaga.com"
            paths:
              - /get
              - /api
            methods:
              - GET
              - POST
            protocols:
              - http
              - https
            strip_path: true
            preserve_host: true
