apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: kong:3.6
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "2Gi"
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: "/kong/declarative/kong.yaml"
            - name: KONG_PROXY_LISTEN
              value: "0.0.0.0:8000 http2, 0.0.0.0:8443 ssl http2"
            - name: KONG_ADMIN_LISTEN
              value: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
            - name: KONG_SSL_CERT
              value: "/etc/secrets/kong/tls.crt"
            - name: KONG_SSL_CERT_KEY
              value: "/etc/secrets/kong/tls.key"
          ports:
            - containerPort: 8000
            - containerPort: 8443
            - containerPort: 8001
            - containerPort: 8444
          volumeMounts:
            - name: kong-config
              mountPath: /kong/declarative
            - name: tls-certs
              mountPath: /etc/secrets/kong
              readOnly: true
      volumes:
        - name: kong-config
          configMap:
            name: kong-declarative-config
        - name: tls-certs
          secret:
            secretName: mlm.nccnaga.com-tls
---
apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: proxy
      port: 80
      targetPort: 8000
    - name: proxy-ssl
      port: 443
      targetPort: 8443
  selector:
    app: kong
---
apiVersion: v1
kind: Service
metadata:
  name: kong-admin
  namespace: default
spec:
  type: ClusterIP
  ports:
    - name: admin
      port: 8001
      targetPort: 8001
    - name: admin-ssl
      port: 8444
      targetPort: 8444
  selector:
    app: kong
