# -------------------------------------------------------------------
# 1. HTTPBin Deployment & Service in default namespace
# -------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - name: httpbin
        image: kennethreitz/httpbin
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: default
spec:
  selector:
    app: httpbin
  ports:
  - port: 80
    targetPort: 80

---
# -------------------------------------------------------------------
# 2. Kong Declarative Config (ConfigMap)
# -------------------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-declarative-config
  namespace: default
data:
  kong.yaml: |
    _format_version: "2.1"
    services:
    - name: httpbin
      url: http://httpbin.default.svc.cluster.local:80
      routes:
      - name: httpbin-route
        hosts:
        - mlm.nccnaga.com

---
# -------------------------------------------------------------------
# 3. Kong Deployment (DB-less with TLS)
# -------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: default
  labels:
    app: ingress-kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-kong
  template:
    metadata:
      labels:
        app: ingress-kong
    spec:
      containers:
      - name: kong
        image: kong:3.4.0
        env:
        - name: KONG_DATABASE
          value: "off"
        - name: KONG_DECLARATIVE_CONFIG
          value: /usr/local/kong/declarative/kong.yaml
        - name: KONG_PROXY_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_ADMIN_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_PROXY_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_LISTEN
          value: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
        - name: KONG_PROXY_LISTEN
          value: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
        ports:
        - containerPort: 8000
          name: proxy
        - containerPort: 8443
          name: proxy-ssl
        - containerPort: 8001
          name: admin
        - containerPort: 8444
          name: admin-ssl
        volumeMounts:
        - name: tls-certs
          mountPath: /etc/secrets/kong
          readOnly: true
        - name: kong-declarative
          mountPath: /usr/local/kong/declarative
          readOnly: true
      volumes:
      - name: tls-certs
        secret:
          secretName: mlm.nccnaga.com-tls
      - name: kong-declarative
        configMap:
          name: kong-declarative-config

---
# -------------------------------------------------------------------
# 4. Kong Services (LoadBalancer + Admin)
# -------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: ingress-kong
  ports:
  - name: proxy
    port: 80
    targetPort: 8000
  - name: proxy-ssl
    port: 443
    targetPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: kong-admin
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: ingress-kong
  ports:
  - name: admin
    port: 8001
    targetPort: 8001
  - name: admin-ssl
    port: 8444
    targetPort: 8444
