apiVersion: v1
kind: Service
metadata:
  name: kong-manager
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: kong
    component: manager
  ports:
    - name: http
      port: 8002
      targetPort: 8002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-manager
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
      component: manager
  template:
    metadata:
      labels:
        app: kong
        component: manager
    spec:
      containers:
        - name: manager
          image: kong:3.9
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: "/kong/declarative/kong.yml"
            - name: KONG_ADMIN_LISTEN
              value: "0.0.0.0:8002 ssl"
            - name: KONG_PROXY_LISTEN
              value: "0.0.0.0:8000, 0.0.0.0:8443 http2 ssl"
            - name: KONG_ADMIN_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_ADMIN_ERROR_LOG
              value: "/dev/stderr"
          ports:
            - containerPort: 8002
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-manager-ingress
  namespace: default
  annotations:
    konghq.com/strip-path: "false"
spec:
  ingressClassName: kong
  rules:
    - host: kong-manager.nccnaga.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kong-manager
                port:
                  number: 8002
  tls:
    - hosts:
        - kong-manager.nccnaga.com
      secretName: kong-manager-tls