_format_version: "2.1"
services:
  - name: httpbin
    url: http://httpbin.default.svc.cluster.local:80
    routes:
      - name: httpbin-route
        hosts:
          - mlm.nccnaga.com
        paths:
          - /
        protocols:
          - https