_format_version: "2.1"

services:
  - name: httpbin
    url: "http://httpbin.default.svc.cluster.local"
    routes:
      - name: httpbin-route
        paths:
          - "/"
        hosts:
          - "mlm.nccnaga.com"
