# argo-kong-httpbin.yaml

# 1️⃣ Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: default
---
# 2️⃣ Kong DB-less ConfigMap (Helm values)
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-values
  namespace: default
data:
  values.yaml: |
    replicaCount: 1
    env:
      KONG_DATABASE: "off"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8444 ssl"  # changed from 127.0.0.1
      KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:8443 http2 ssl"
      KONG_STATUS_LISTEN: "0.0.0.0:8100"
    ingressController:
      enabled: true
      ingressClass: kong
      publishService:
        enabled: true
      replicaCount: 1
      containerSecurityContext:
        runAsUser: 101
        runAsNonRoot: true
      admissionWebhooks:
        enabled: false
    proxy:
      type: LoadBalancer
      http:
        enabled: true
        servicePort: 80
      tls:
        enabled: true
        servicePort: 443
    admin:
      enabled: true
      http:
        enabled: true
        host: 0.0.0.0   # changed from 127.0.0.1
        port: 8444
      tls:
        enabled: true
---
# 4️⃣ HTTPBIN Ingress with TLS
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin-ingress
  namespace: default
  annotations:
    konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  tls:
    - hosts:
        - mlm.nccnaga.com
      secretName: mlm.nccnaga.com-tls
  rules:
    - host: mlm.nccnaga.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: httpbin
                port:
                  number: 80   # removed trailing dot
