apiVersion: apps/v1
kind: Deployment
metadata:
  name: lotto-authen
spec:
  selector:
    matchLabels:
      app: lotto-authen
  template:
    metadata:
      labels:
        app: lotto-authen
    spec:
      containers:
        - name: lotto-authen
          image: newconceptconsulting/lotto_naga_auth:1.2.48 #47 #36 #35 #33 #21 #21 #20 #19 #18 #14 #9
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
          env:
          # # PG_BOUNCER_lotto_USER
          #   - name: PG_HOST
          #     valueFrom:
          #       secretKeyRef:
          #         name: lotto-pgbouncer-user-secret
          #         key: PG_HOST
          #   - name: PG_PORT
          #     valueFrom:
          #       secretKeyRef:
          #         name: lotto-pgbouncer-user-secret
          #         key: PG_PORT
          #   - name: PG_USER
          #     valueFrom:
          #       secretKeyRef:
          #         name: lotto-pgbouncer-user-secret
          #         key: PG_USER
          #   - name: PG_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: lotto-pgbouncer-user-secret
          #         key: PG_PASSWORD
          #   - name: PG_DATABASESESSIONUSER
          #     valueFrom:
          #       secretKeyRef:
          #         name: lotto-pgbouncer-user-secret
          #         key: PG_DATABASESESSIONUSER

          #   # redis
          #   - name: REDIS_HOST
          #     value: redis-service
          #   - name: REDIS_PORT
          #     value: "6379"
          #   # winning
          #   - name: WIN_HOST
          #     value: "http://lotto-winning-services"
          #   - name: WIN_PORT
          #     value: "8811"
          #   # BUYLOTTO6
          #   - name: LOTTO6_HOST
          #     value: "http://lotto-buylotto2d6d-services"
          #   - name: LOTTO6_PORT
          #     value: "8814"
          #   # BUYLOTTO4
          #   - name: LOTTO4_HOST
          #     value: "http://lotto-buylotto440-services"
          #   - name: LOTTO4_PORT
          #     value: "8815"
          #   # LOTTODELETE6
          #   - name: LOTTO6DELETE_HOST
          #     value: "http://lotto-delete-2d6d-services"
          #   - name: LOTTO6DELETE_PORT
          #     value: "8816"
          #   # LOTTODELETE4
          #   - name: LOTTO4DELETE_HOST
          #     value: "http://lotto-delete-440-services"
          #   - name: LOTTO4DELETE_PORT
          #     value: "8817"
          #   # REPORT
          #   - name: REPORT_HOST
          #     value: "http://lotto-report-services"
          #   - name: REPORT_PORT
          #     value: "8813"
          #   # GET_BILL
          #   - name: BILL_HOST
          #     value: "http://lotto-get-bill-services"
          #   - name: BILL_PORT
          #     value: "8818"
          #   #COMPARE
          #   - name: COMPARE_HOST
          #     value: "http://lotto-compare-report-services"
          #   - name: COMPARE_PORT
          #     value: "8820"
          #   #BCEL_TICKET
          #   - name: TICKET_HOST
          #     value: "http://lotto-bcel-lotto-ticket-services"
          #   - name: TICKET_PORT
          #     value: "9954"

          ports:
            - containerPort: 8812
      imagePullSecrets:
        - name: docker-hub
---
apiVersion: v1
kind: Service
metadata:
  name: lotto-authen-services
spec:
  type: ClusterIP
  selector:
    app: lotto-authen
  ports:
    - port: 8812
      targetPort: 8812
